In [17]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/shayanhusain/drug-food-interactions-dataset/Drug to Food interactions Dataset.json

In [18]:
df = pd.read_json("/kaggle/input/datasets/shayanhusain/drug-food-interactions-dataset/Drug to Food interactions Dataset.json")
print(df.shape)   
print(df.head())

(1423, 3)
                    name                                          reference  \
0              Lepirudin  Knox C, Wilson M, Klinger CM, et al. DrugBank ...
1            Bivalirudin  Knox C, Wilson M, Klinger CM, et al. DrugBank ...
2  Peginterferon alfa-2a  Knox C, Wilson M, Klinger CM, et al. DrugBank ...
3              Alteplase  Knox C, Wilson M, Klinger CM, et al. DrugBank ...
4     Interferon alfa-n1  Knox C, Wilson M, Klinger CM, et al. DrugBank ...

                                   food_interactions
0  [Avoid herbs and supplements with anticoagulan...
1  [Avoid echinacea., Avoid herbs and supplements...
2                          [Drink plenty of fluids.]
3  [Avoid herbs and supplements with anticoagulan...
4                                   [Avoid alcohol.]

In [19]:
df.head()

,name,reference,food_interactions
0,Lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",[Avoid herbs and supplements with anticoagulan...
1,Bivalirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...","[Avoid echinacea., Avoid herbs and supplements..."
2,Peginterferon alfa-2a,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",[Drink plenty of fluids.]
3,Alteplase,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",[Avoid herbs and supplements with anticoagulan...
4,Interferon alfa-n1,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",[Avoid alcohol.]

In [20]:
df.describe()

,name,reference,food_interactions
count,1423,1423,1423
unique,1423,1,1003
top,Benzgalantamine,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",[Take with or without food.]
freq,1,1423,76

In [21]:
interaction_counts = df['food_interactions'].value_counts()
print("Interaction type distribution:\n", interaction_counts)

Interaction type distribution:
 food_interactions
[Take with or without food.]                                                                                                                                                                                                                          76
[Take with or without food. The absorption is unaffected by food.]                                                                                                                                                                                    70
[Avoid herbs and supplements with anticoagulant/antiplatelet activity. Examples include garlic, ginger, bilberry, danshen, piracetam, and ginkgo biloba.]                                                                                             49
[Take with food.]                                                                                                                                                                                                                                     34
[Avoid alcohol., Take with food. Food reduces irritation.]                                                                                                                                                                                            27
                                                                                                                                                                                                                                                      ..
[Take with or without food. Administration with a high-fat meal decreases the rate and extent of absorption, but not to a clinically significant degree.]                                                                                              1
[Take with or without food. Food has negligible effects on systemic exposure of leniolisib.]                                                                                                                                                           1
[Take with or without food. Food does not have a clinically significant effect on lazertinib pharmacokinetics.]                                                                                                                                        1
[Administer vitamin supplements. Inform patients that eplontersen treatment leads to a decrease in vitamin A levels, and supplementation of vitamin A at the recommended daily allowance is recommended.]                                              1
[Avoid grapefruit products. Grapefruit products may increase exposure to finerenone, increasing the risk and severity of adverse effects., Take with or without food. Food does not have a clinically significant effect on area under the curve.]     1
Name: count, Length: 1003, dtype: int64

In [22]:
missing_mechanism = (
    df.groupby('name')['food_interactions']
      .apply(lambda x: x.isna().mean() * 100)  # percentage missing
      .sort_values(ascending=False)
)
print("Missing food_interactions % per drug:\n", missing_mechanism)

Missing food_interactions % per drug:
 name
Zuranolone              0.0
(R)-warfarin            0.0
(S)-Warfarin            0.0
Abacavir                0.0
Abaloparatide           0.0
                       ...
Acetylsalicylic acid    0.0
Acetohydroxamic acid    0.0
Acetohexamide           0.0
Acetazolamide           0.0
Acetaminophen           0.0
Name: food_interactions, Length: 1423, dtype: float64

In [23]:
print("Total rows:", len(df))
print("Unique drugs:", df['name'].nunique())

Total rows: 1423
Unique drugs: 1423